version: '3.8'

services:
  open-sonar:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-sonar
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=INFO
      - AUTH_TOKEN=${AUTH_TOKEN:-test-token}
      - OLLAMA_HOST=http://ollama:11434  # Explicitly force this to use container name
      - OLLAMA_MODEL=${OLLAMA_MODEL:-deepseek-r1:1.5b}
    networks:
      - open-sonar-network
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - open-sonar-network

networks:
  open-sonar-network:
    name: open-sonar-network

volumes:
  ollama-data:
    name: ollama-data
